/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

// CSS side-effect imports (TypeScript 6.0 requires explicit declarations)
declare module '*.css' {}